# Generated by Django 3.0.8 on 2020-08-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ggg_art.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_generic_catalog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ggg_art.utilities.artist_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('release_date', models.DateTimeField()),
                ('height', models.DecimalField(decimal_places=3, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=8)),
                ('art_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ggg_art.ArtCategory')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ggg_art.Artist')),
            ],
            options={
                'ordering': ('artist', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ggg_art.utilities.location_directory_path)),
                ('profit_share', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores_controlled_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PrintedArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available', models.BooleanField(default=False)),
                ('artwork_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_artworks', to='ggg_art.Artwork')),
                ('displayed_at', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='printed_artworks', to='ggg_art.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available', models.BooleanField(default=False)),
                ('artwork_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='ggg_art.Artwork', unique=True)),
                ('displayed_at', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='original', to='ggg_art.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LimitedArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available', models.BooleanField(default=False)),
                ('artwork_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_artworks', to='ggg_art.Artwork')),
                ('displayed_at', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='limited_artworks', to='ggg_art.Location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ggg_art.Technique'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='product_generic_catalog.ProductGenericClass'),
        ),
    ]
