# Generated by Django 3.0.8 on 2020-08-04 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('release_date', models.DateTimeField()),
                ('height', models.DecimalField(decimal_places=3, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=8)),
                ('art_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ggg_art.ArtCategory')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ggg_art.Artist')),
            ],
            options={
                'ordering': ('artist', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PrintedArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_printed', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=False)),
                ('artwork_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_artworks', to='ggg_art.Artwork')),
                ('displayed_at', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='printed_artworks', to='ggg_art.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available', models.BooleanField(default=False)),
                ('artwork_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='ggg_art.Artwork')),
                ('displayed_at', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='original', to='ggg_art.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LimitedArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available', models.BooleanField(default=False)),
                ('artwork_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_artworks', to='ggg_art.Artwork')),
                ('displayed_at', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='limited_artworks', to='ggg_art.Location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ggg_art.Technique'),
        ),
    ]
