# Generated by Django 3.0.8 on 2020-08-05 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ggg_art.utilities


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ggg_art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ggg_art.utilities.artist_directory_path),
        ),
        migrations.AlterField(
            model_name='originalartwork',
            name='artwork_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='ggg_art.Artwork', unique=True),
        ),
        migrations.AlterField(
            model_name='originalartwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
