# Generated by Django 3.0.8 on 2020-08-28 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('segment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_categories', to='generic_vendor_profiles.GlobalSegment')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_categories', to='generic_vendor_profiles.VendorCategory')),
            ],
        ),
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF')], max_length=4)),
                ('vendor_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='generic_vendor_profiles.VendorSubCategory')),
                ('vendor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
